CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    logo_url VARCHAR(512),
    budget_available NUMERIC(19, 2) NOT NULL DEFAULT 0,
    budget_allocated NUMERIC(19, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    email VARCHAR(180) NOT NULL,
    password_hash VARCHAR(120) NOT NULL,
    full_name VARCHAR(160) NOT NULL,
    role VARCHAR(32) NOT NULL,
    avatar_url VARCHAR(512),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE INDEX idx_users_org ON users (organization_id);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    email VARCHAR(180) NOT NULL,
    role VARCHAR(32) NOT NULL,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    name VARCHAR(180) NOT NULL,
    type VARCHAR(80) NOT NULL,
    category VARCHAR(80) NOT NULL,
    criticality VARCHAR(32) NOT NULL,
    risk_score NUMERIC(6, 2) NOT NULL DEFAULT 0,
    financial_exposure NUMERIC(19, 2) NOT NULL DEFAULT 0,
    owner VARCHAR(160),
    last_scanned_at TIMESTAMP,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_assets_org ON assets (organization_id);

CREATE TABLE vulnerabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    asset_id BIGINT NOT NULL REFERENCES assets (id),
    title VARCHAR(240) NOT NULL,
    description TEXT,
    severity VARCHAR(32) NOT NULL,
    cve_id VARCHAR(40),
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    discovered_date DATE NOT NULL,
    remediation_deadline DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_vulns_org ON vulnerabilities (organization_id);

CREATE TABLE threat_intel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    title VARCHAR(240) NOT NULL,
    threat_actor VARCHAR(160),
    threat_type VARCHAR(80),
    severity VARCHAR(32) NOT NULL,
    source VARCHAR(160),
    published_date DATE NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE threat_intel_assets (
    threat_id BIGINT NOT NULL REFERENCES threat_intel (id) ON DELETE CASCADE,
    asset_id BIGINT NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
    PRIMARY KEY (threat_id, asset_id)
);

CREATE TABLE risk_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    snapshot_date DATE NOT NULL,
    overall_score NUMERIC(6, 2) NOT NULL,
    financial_exposure NUMERIC(19, 2) NOT NULL,
    CONSTRAINT uk_risk_snap UNIQUE (organization_id, snapshot_date)
);

CREATE TABLE remediation_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    name VARCHAR(200) NOT NULL,
    description TEXT,
    cost NUMERIC(19, 2) NOT NULL,
    risk_reduction_percent NUMERIC(6, 2) NOT NULL,
    category VARCHAR(80),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE applied_investments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    action_id BIGINT NOT NULL REFERENCES remediation_actions (id),
    cost NUMERIC(19, 2) NOT NULL,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE whatif_scenarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    name VARCHAR(200) NOT NULL,
    description TEXT,
    control_id BIGINT REFERENCES remediation_actions (id),
    delay_days INT NOT NULL DEFAULT 30
);

CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    title VARCHAR(240) NOT NULL,
    message TEXT,
    severity VARCHAR(32) NOT NULL,
    read BOOLEAN NOT NULL DEFAULT FALSE,
    asset_id BIGINT REFERENCES assets (id),
    vulnerability_id BIGINT REFERENCES vulnerabilities (id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_alerts_org ON alerts (organization_id);

CREATE TABLE billing_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    price_monthly NUMERIC(19, 2) NOT NULL,
    features TEXT NOT NULL
);

CREATE TABLE organization_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL UNIQUE REFERENCES organizations (id),
    plan_id BIGINT NOT NULL REFERENCES billing_plans (id),
    renewal_date DATE NOT NULL
);

CREATE TABLE payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    brand VARCHAR(40) NOT NULL,
    last4 VARCHAR(8) NOT NULL,
    method_type VARCHAR(40) NOT NULL,
    gateway_token VARCHAR(180),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    invoice_number VARCHAR(40) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(32) NOT NULL,
    issued_at DATE NOT NULL,
    pdf_path VARCHAR(512)
);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    created_by BIGINT REFERENCES users (id),
    report_type VARCHAR(40) NOT NULL,
    format VARCHAR(12) NOT NULL,
    file_path VARCHAR(512) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notification_preferences (
    user_id BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    email_alerts BOOLEAN NOT NULL DEFAULT TRUE,
    in_app_alerts BOOLEAN NOT NULL DEFAULT TRUE,
    weekly_digest BOOLEAN NOT NULL DEFAULT TRUE
);
